#!/usr/bin/env bash
export CUMULUS_DIR=$(pwd)
function cumulus {
  $CUMULUS_DIR/bin/cumulus.rb "$@"
}

function _cumulus {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=${COMP_WORDS[COMP_CWORD-1]}
  local twoprev=${COMP_WORDS[COMP_CWORD-2]}
  local threeprev=${COMP_WORDS[COMP_CWORD-3]}

  case "$threeprev" in
    iam)
        if [ "$prev" == "diff" ] || [ "$prev" == "sync" ]; then
          configs=$($CUMULUS_DIR/bin/cumulus.rb iam "$twoprev" list)
          COMPREPLY=( $(compgen -W "$configs" -- $cur ) )
        fi
    ;;
    *)
      case "$twoprev" in
        iam)
          COMPREPLY=( $(compgen -W "diff list sync" -- $cur) )
        ;;
        *)
          case "$prev" in
            iam)
              COMPREPLY=( $(compgen -W "roles users" -- $cur) )
            ;;
            cumulus)
              COMPREPLY=( $(compgen -W "help iam" -- $cur) )
            ;;
          esac
        ;;
      esac
  esac
}
complete -F _cumulus cumulus
